### ISSUE TITLE
chinese-text-correction-7b 需要多大的显存

### ISSUE THREAD

**Issue by dexter-lib** [shibing624/pycorrector#537]
我们尝试在A800 80G卡上运行 chinese-text-correction-7b，报错：torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 GiB (GPU 3; 79.35 GiB total capacity; 31.14 GiB already allocated; 47.11 GiB free; 71.41 GiB allowed; 31.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF，请问这个chinese-text-correction-7b 到底需要多大的显存才能跑起来。

**Comment by shibing624** [comment]
bf16, 26GB就可以跑起来。

**Comment by dexter-lib** [comment]
这个问题已解决，还是cuda驱动版本和pytorch不匹配导致的，我又换了一个A40的显卡，现在跑的没问题，感谢作者。
